version: "3.9"

services:
  # Microservicio de Autenticación
  authentication:
    build:
      context: ./authentication   
      dockerfile: deployment/Dockerfile
    container_name: authentication-service
    ports:
      - "8090:8090"  
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_auth:5432/authentication
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db_auth
    networks:
      - backend

  # Base de datos para Autenticación
  db_auth:
    image: postgres:15
    container_name: db_auth
    restart: always
    environment:
      POSTGRES_DB: authentication
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - db_auth_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" 
    networks:
      - backend

  # Microservicio de Orders
  orders:
    build:
      context: ./orders   
      dockerfile: deployment/Dockerfile
    container_name: orders-service
    ports:
      - "8091:8091"   
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_orders:5432/orders
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db_orders
      - authentication 
    networks:
      - backend

  # Base de datos para Orders
  db_orders:
    image: postgres:15
    container_name: db_orders
    restart: always
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - db_orders_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - backend

networks:
  backend:

volumes:
  db_auth_data:
  db_orders_data:
