server:
  port: ${AUTH_PORT:8090}
  application:
    name: "Authentication"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
springdoc:
  api-docs:
    path: /api/doc/api-docs
  swagger-ui:
    path: /api/doc/swagger-ui.html
adapters:
  r2dbc:
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:5432}
    database: ${DB_AUTH_NAME:authentication}
    schema: "public"
    username: ${DB_USER:postgres}
    password:  ${DB_PASSWORD:root}
liquibase:
  change-log: classpath:db/changelog/db.changelog-master.yaml
  enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8090"
logging:
  level:
    root: INFO
  file:
    name: logs/crediya_auth.log
jwt:
  secret: "HsTqW3BTS2qT/U8L8K5l8wV7Q8H3q0EoM7R0JbHcBjc="
  expiration-ms: 3600000
